sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IDg4tXc27P6rPJr0Af0rYdnRxz/YbwyleLvbusY4IaYHxnEHG2MnMGlwcP64EtGXDhfoGSPLbsoD9cg0yS0UChWFDIbO0eJJhhTiRLYoju7B1XmWdEwk2NHfyPmTBoXolwhBypGiTRQE4i+DDjGBOtXYfpeeoZ9CIGM8tCjBpBianpWJv0VR1i3+0l7dzB2K2BZTcvUZhBjsrNlxEXHI52S3vO2tV8/2LKXbmhIPFAMJkRz67iT04Vjl/CQYxYACBN0WdWb2xn9GWdhWi4ycryNpzrTYmbI7u5Pk5bA6cgXU4RKTgfFu8CUhvQ45za4/PimArKv+Y7ECRzB889iAFGDVO45UiIZqXQ+/5p3uGKEAiwrTWlcA08qXxQ9PpCRni4VmuFGYxk+0ip3/Zi6OVFaf05G8DrJauyZiDkQ+E5WvfEGKby6eMsy0KGj0M/LnlXYnbKxL3IhBRDMBcrX1HIb5b26g/F9mclsY5yDlACLzLvpQKbZIlJRXn8JMaO57+0ZLO8/qIsWojuMFcDXHNMSbIBAbC9qVTARybrMJrx195s7hETQibrAAnl+g+kxy7ZdFz4HJ2UNLnZasWoK7NjEKZlRGqPMiH/Zlin44J6OtWuhX+Kk/qGIvnveieyfjWvqhkR6JgXTj7u7RY9t5ICgnbyQnSGzBQvP0ujHrfpA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-History-of-Don-Quixote-Volume-2-Part-40_5943
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy